--Esquema pais PERU
BEGIN;
    --registra la catidad de digitos para facturacion
    UPDATE PUBLIC.saepais 
	SET pais_codigo_inter = '51', pais_dig_sere = '4', pais_dig_face = '9' ,pais_dig_autoe = '0', pais_dig_serp = '4', pais_dig_facp = '9' ,pais_dig_autop = '0'
	where pais_cod_pais =28;
    --configuracion de moneda por pais
    UPDATE public.saemone SET mone_cod_empr = 1, mone_des_mone = 'SOLES', mone_sgl_mone = 'PEN', mone_smb_mene = 'S/', mone_est_mone = '1', mone_cod_pais = 28 WHERE mone_cod_mone = 1;
    UPDATE public.saemone SET mone_cod_empr = 1, mone_des_mone = 'DOLAR', mone_sgl_mone = 'USD', mone_smb_mene = '$', mone_est_mone = '1', mone_cod_pais = 7 WHERE mone_cod_mone = 2;
    --etiquetas por pais
    DELETE from comercial.pais_etiq_imp;
    INSERT INTO comercial.pais_etiq_imp (pais_cod_pais, pais_codigo_inter, impuesto, etiqueta, porcentaje, porcentaje2) VALUES (28, '51', 'IVA', 'IGV', 18, 0);
    INSERT INTO comercial.pais_etiq_imp (pais_cod_pais, pais_codigo_inter, impuesto, etiqueta, porcentaje, porcentaje2) VALUES (28, '51', 'ICE', 'ICE', 0, 0);
    INSERT INTO comercial.pais_etiq_imp (pais_cod_pais, pais_codigo_inter, impuesto, etiqueta, porcentaje, porcentaje2) VALUES (28, '51', 'IRBP', 'IRBP', 0, 0);
    INSERT INTO comercial.pais_etiq_imp (pais_cod_pais, pais_codigo_inter, impuesto, etiqueta, porcentaje, porcentaje2) VALUES (28, '51', 'RETENCION', 'DET/RET', 0, 0);
    INSERT INTO comercial.pais_etiq_imp (pais_cod_pais, pais_codigo_inter, impuesto, etiqueta, porcentaje, porcentaje2) VALUES (28, '51', 'TIPO_RETENCION', 'DETR', 0, 0);
    INSERT INTO comercial.pais_etiq_imp (pais_cod_pais, pais_codigo_inter, impuesto, etiqueta, porcentaje, porcentaje2) VALUES (28, '51', 'DECIMALES_RETENCION', '2', 0, 0);

    -- Eliminar registros existentes
    DELETE FROM comercial.tipo_iden_clpv_pais WHERE pais_cod_pais = 28;

    -- Insertar nuevos registros
    INSERT INTO comercial.tipo_iden_clpv_pais (id_iden_pais, id_iden_clpv, pais_cod_pais, pais_des_pais, identificacion, digitos, pais_codigo_inter, extranjero, checked, cf_sn, cf_numero, codigo_libro) VALUES (31, 1, 28, 'PERU', 'RUC', 11, '51', 0, NULL, 'N', NULL, NULL);
    INSERT INTO comercial.tipo_iden_clpv_pais (id_iden_pais, id_iden_clpv, pais_cod_pais, pais_des_pais, identificacion, digitos, pais_codigo_inter, extranjero, checked, cf_sn, cf_numero, codigo_libro) VALUES (32, 2, 28, 'PERU', 'DNI', 8, '51', 0, NULL, 'N', NULL, NULL);
    INSERT INTO comercial.tipo_iden_clpv_pais (id_iden_pais, id_iden_clpv, pais_cod_pais, pais_des_pais, identificacion, digitos, pais_codigo_inter, extranjero, checked, cf_sn, cf_numero, codigo_libro) VALUES (33, 3, 28, 'PERU', 'EXTRANJERA', 12, '51', 0, NULL, 'N', NULL, NULL);
    INSERT INTO comercial.tipo_iden_clpv_pais (id_iden_pais, id_iden_clpv, pais_cod_pais, pais_des_pais, identificacion, digitos, pais_codigo_inter, extranjero, checked, cf_sn, cf_numero, codigo_libro) VALUES (34, 3, 28, 'PERU', 'CPP', 9, '51', 0, NULL, 'N', NULL, NULL);

    -- Actualizar configuración de geografía para distribución de creación de contrato
    DELETE FROM comercial.pais_etiq_contr;
    INSERT INTO comercial.pais_etiq_contr (id, pais_cod_pais, pais_etiq_pais, pais_tbl_direc, pais_etiq_est) VALUES (1, 28, 'DEPARTAMENTO', 'saeprov', 'A');
    INSERT INTO comercial.pais_etiq_contr (id, pais_cod_pais, pais_etiq_pais, pais_tbl_direc, pais_etiq_est) VALUES (2, 28, 'PROVINCIA', 'saecant', 'A');
    INSERT INTO comercial.pais_etiq_contr (id, pais_cod_pais, pais_etiq_pais, pais_tbl_direc, pais_etiq_est) VALUES (3, 28, 'PROVINCIA', 'saeciud', 'I');
    INSERT INTO comercial.pais_etiq_contr (id, pais_cod_pais, pais_etiq_pais, pais_tbl_direc, pais_etiq_est) VALUES (4, 28, 'DISTRITO', 'saeparr', 'A');
COMMIT;

--motivos de las notas de credito para pais peru

BEGIN;
    DELETE from public.saeddev;
    INSERT INTO public.saeddev (ddev_cod_ddev, ddev_cod_empr, ddev_des_ddev, ddev_tip_ddev) VALUES (1, 1, 'Anulación de la Operación', '01');
    INSERT INTO public.saeddev (ddev_cod_ddev, ddev_cod_empr, ddev_des_ddev, ddev_tip_ddev) VALUES (2, 1, 'Anulación por Error en el RUC', '02');
    INSERT INTO public.saeddev (ddev_cod_ddev, ddev_cod_empr, ddev_des_ddev, ddev_tip_ddev) VALUES (3, 1, 'Descuento Global', '04');
    INSERT INTO public.saeddev (ddev_cod_ddev, ddev_cod_empr, ddev_des_ddev, ddev_tip_ddev) VALUES (4, 1, 'Devolución Total', '06');
    INSERT INTO public.saeddev (ddev_cod_ddev, ddev_cod_empr, ddev_des_ddev, ddev_tip_ddev) VALUES (5, 1, 'Corrección por error en la descripcion', '03');
    INSERT INTO public.saeddev (ddev_cod_ddev, ddev_cod_empr, ddev_des_ddev, ddev_tip_ddev) VALUES (6, 1, 'Devolución por ítem', '07');
    INSERT INTO public.saeddev (ddev_cod_ddev, ddev_cod_empr, ddev_des_ddev, ddev_tip_ddev) VALUES (13, 1, 'Descuento por ítem', '05');
    INSERT INTO public.saeddev (ddev_cod_ddev, ddev_cod_empr, ddev_des_ddev, ddev_tip_ddev) VALUES (14, 1, 'Bonificación', '08');
    INSERT INTO public.saeddev (ddev_cod_ddev, ddev_cod_empr, ddev_des_ddev, ddev_tip_ddev) VALUES (15, 1, 'Disminución en el valor', '09');
    INSERT INTO public.saeddev (ddev_cod_ddev, ddev_cod_empr, ddev_des_ddev, ddev_tip_ddev) VALUES (19, 1, 'Otros conceptos', '10');
    INSERT INTO public.saeddev (ddev_cod_ddev, ddev_cod_empr, ddev_des_ddev, ddev_tip_ddev) VALUES (21, 1, 'Ajustes afectos al IVAP', '12');
    INSERT INTO public.saeddev (ddev_cod_ddev, ddev_cod_empr, ddev_des_ddev, ddev_tip_ddev) VALUES (23, 1, 'Ajustes de operaciones de exportación', '11');
    INSERT INTO public.saeddev (ddev_cod_ddev, ddev_cod_empr, ddev_des_ddev, ddev_tip_ddev) VALUES (25, 1, 'Correción del monto neto pendiente de pago y/o las fechas de vencimiento del pago único o de las cuotas y /o los montos correspondientes a cada cuota, de ser el caso', '13');
    --APLICAR SI EL PROYECTO TIENE TRASACCIONES
    UPDATE public.saeclpv SET clpv_cod_vend = NULL, clpv_cod_zona = NULL, clpv_cod_ciud = NULL WHERE clpv_cod_sucu != 0 AND clpv_cod_empr != 0;
    UPDATE public.saevend SET zona_cod_zona = NULL, vend_cod_ciu = NULL WHERE vend_cod_empr != 0;
    UPDATE public.saeempl SET empl_cod_ciud = NULL WHERE empl_cod_empr != 0;
    UPDATE public.saeestr SET estr_cod_ciud = NULL WHERE estr_cod_empr != 0;
COMMIT;

BEGIN;
    DELETE FROM public.saeparr;
    DELETE FROM public.saeciud;
    DELETE FROM public.saecant;
    DELETE FROM public.saeprov;
    DELETE FROM public.saezona;
    --CREATE SEQUENCE saezona_zona_cod_zona_seq; 
    --ALTER SEQUENCE public.saezona_zona_cod_zona_seq RESTART WITH 1;
    INSERT INTO public.saezona (zona_cod_empr, zona_cod_sucu, zona_nom_zona, zona_opc_zona, zona_cod_ciud) 
        VALUES 
                (1, 1, 'AMAZONAS', NULL, NULL ),
                (1, 1, 'ÁNCASH', NULL, NULL ),
                (1, 1, 'APURÍMAC', NULL, NULL ),
                (1, 1, 'AREQUIPA', NULL, NULL ),
                (1, 1, 'AYACUCHO', NULL, NULL ),
                (1, 1, 'CAJAMARCA', NULL, NULL ),
                (1, 1, 'PROV. CONST. DEL CALLAO', NULL, NULL ),
                (1, 1, 'CUSCO', NULL, NULL ),
                (1, 1, 'HUANCAVELICA', NULL, NULL ),
                (1, 1, 'HUÁNUCO', NULL, NULL ),
                (1, 1, 'ICA', NULL, NULL ),
                (1, 1, 'JUNÍN', NULL, NULL ),
                (1, 1, 'LA LIBERTAD', NULL, NULL ),
                (1, 1, 'LAMBAYEQUE', NULL, NULL ),
                (1, 1, 'LIMA ', NULL, NULL ),
                (1, 1, 'LORETO', NULL, NULL ),
                (1, 1, 'MADRE DE DIOS', NULL, NULL ),
                (1, 1, 'MOQUEGUA', NULL, NULL ),
                (1, 1, 'PASCO', NULL, NULL ),
                (1, 1, 'PIURA', NULL, NULL ),
                (1, 1, 'PUNO', NULL, NULL ),
                (1, 1, 'SAN MARTÍN', NULL, NULL ),
                (1, 1, 'TACNA', NULL, NULL ),
                (1, 1, 'TUMBES', NULL, NULL ),
                (1, 1, 'UCAYALI', NULL, NULL );
    INSERT INTO public.saeprov (prov_cod_prov, prov_des_prov,prov_cod_char) 
        VALUES 
                (1, 'AMAZONAS', '01'),
                (2, 'ÁNCASH', '02'),
                (3, 'APURÍMAC', '03'),
                (4, 'AREQUIPA', '04'),
                (5, 'AYACUCHO', '05'),
                (6, 'CAJAMARCA', '06'),
                (7, 'PROV. CONST. DEL CALLAO', '07'),
                (8, 'CUSCO', '08'),
                (9, 'HUANCAVELICA', '09'),
                (10, 'HUÁNUCO', '10'),
                (11, 'ICA', '11'),
                (12, 'JUNÍN', '12'),
                (13, 'LA LIBERTAD', '13'),
                (14, 'LAMBAYEQUE', '14'),
                (15, 'LIMA', '15'),
                (16, 'LORETO', '16'),
                (17, 'MADRE DE DIOS', '17'),
                (18, 'MOQUEGUA', '18'),
                (19, 'PASCO', '19'),
                (20, 'PIURA', '20'),
                (21, 'PUNO', '21'),
                (22, 'SAN MARTÍN', '22'),
                (23, 'TACNA', '23'),
                (24, 'TUMBES', '24'),
                (25, 'UCAYALI', '25');
    INSERT INTO public.saecant (cant_cod_cant, cant_cod_char, cant_des_cant, cant_sri_codi, cant_cod_provc, cant_cod_prov, cant_est_cant) 
        VALUES  
                (1, '01', 'CHACHAPOYAS', '', '', 1, 'A'),
                (2, '02', 'BAGUA', '', '', 1, 'A'),
                (3, '03', 'BONGARÁ', '', '', 1, 'A'),
                (4, '04', 'CONDORCANQUI', '', '', 1, 'A'),
                (5, '05', 'LUYA', '', '', 1, 'A'),
                (6, '06', 'RODRÍGUEZ DE MENDOZA', '', '', 1, 'A'),
                (7, '07', 'UTCUBAMBA', '', '', 1, 'A'),
                (8, '01', 'HUARAZ', '', '', 2, 'A'),
                (9, '02', 'AIJA', '', '', 2, 'A'),
                (10, '03', 'ANTONIO RAYMONDI', '', '', 2, 'A'),
                (11, '04', 'ASUNCIÓN', '', '', 2, 'A'),
                (12, '05', 'BOLOGNESI', '', '', 2, 'A'),
                (13, '06', 'CARHUAZ', '', '', 2, 'A'),
                (14, '07', 'CARLOS F. FITZCARRALD', '', '', 2, 'A'),
                (15, '08', 'CASMA', '', '', 2, 'A'),
                (16, '09', 'CORONGO', '', '', 2, 'A'),
                (17, '10', 'HUARI', '', '', 2, 'A'),
                (18, '11', 'HUARMEY', '', '', 2, 'A'),
                (19, '12', 'HUAYLAS', '', '', 2, 'A'),
                (20, '13', 'MARISCAL LUZURIAGA', '', '', 2, 'A'),
                (21, '14', 'OCROS', '', '', 2, 'A'),
                (22, '15', 'PALLASCA', '', '', 2, 'A'),
                (23, '16', 'POMABAMBA', '', '', 2, 'A'),
                (24, '17', 'RECUAY', '', '', 2, 'A'),
                (25, '18', 'SANTA', '', '', 2, 'A'),
                (26, '19', 'SIHUAS', '', '', 2, 'A'),
                (27, '20', 'YUNGAY', '', '', 2, 'A'),
                (28, '01', 'ABANCAY', '', '', 3, 'A'),
                (29, '02', 'ANDAHUAYLAS', '', '', 3, 'A'),
                (30, '03', 'ANTABAMBA', '', '', 3, 'A'),
                (31, '04', 'AYMARAES', '', '', 3, 'A'),
                (32, '05', 'COTABAMBAS', '', '', 3, 'A'),
                (33, '06', 'CHINCHEROS', '', '', 3, 'A'),
                (34, '07', 'GRAU', '', '', 3, 'A'),
                (35, '01', 'AREQUIPA', '', '', 4, 'A'),
                (36, '02', 'CAMANÁ', '', '', 4, 'A'),
                (37, '03', 'CARAVELÍ', '', '', 4, 'A'),
                (38, '04', 'CASTILLA', '', '', 4, 'A'),
                (39, '05', 'CAYLLOMA', '', '', 4, 'A'),
                (40, '06', 'CONDESUYOS', '', '', 4, 'A'),
                (41, '07', 'ISLAY', '', '', 4, 'A'),
                (42, '08', 'LA UNIÓN', '', '', 4, 'A'),
                (43, '01', 'HUAMANGA', '', '', 5, 'A'),
                (44, '02', 'CANGALLO', '', '', 5, 'A'),
                (45, '03', 'HUANCA SANCOS', '', '', 5, 'A'),
                (46, '04', 'HUANTA', '', '', 5, 'A'),
                (47, '05', 'LA MAR', '', '', 5, 'A'),
                (48, '06', 'LUCANAS', '', '', 5, 'A'),
                (49, '07', 'PARINACOCHAS', '', '', 5, 'A'),
                (50, '08', 'PÁUCAR DEL SARA SARA', '', '', 5, 'A'),
                (51, '09', 'SUCRE', '', '', 5, 'A'),
                (52, '10', 'VÍCTOR FAJARDO', '', '', 5, 'A'),
                (53, '11', 'VILCAS HUAMÁN', '', '', 5, 'A'),
                (54, '01', 'CAJAMARCA', '', '', 6, 'A'),
                (55, '02', 'CAJABAMBA', '', '', 6, 'A'),
                (56, '03', 'CELENDÍN', '', '', 6, 'A'),
                (57, '04', 'CHOTA', '', '', 6, 'A'),
                (58, '05', 'CONTUMAZÁ', '', '', 6, 'A'),
                (59, '06', 'CUTERVO', '', '', 6, 'A'),
                (60, '07', 'HUALGAYOC', '', '', 6, 'A'),
                (61, '08', 'JAÉN', '', '', 6, 'A'),
                (62, '09', 'SAN IGNACIO', '', '', 6, 'A'),
                (63, '10', 'SAN MARCOS', '', '', 6, 'A'),
                (64, '11', 'SAN MIGUEL', '', '', 6, 'A'),
                (65, '12', 'SAN PABLO', '', '', 6, 'A'),
                (66, '13', 'SANTA CRUZ', '', '', 6, 'A'),
                (67, '01', 'CALLAO', '', '', 7, 'A'),
                (68, '01', 'CUSCO', '', '', 8, 'A'),
                (69, '02', 'ACOMAYO', '', '', 8, 'A'),
                (70, '03', 'ANTA', '', '', 8, 'A'),
                (71, '04', 'CALCA', '', '', 8, 'A'),
                (72, '05', 'CANAS', '', '', 8, 'A'),
                (73, '06', 'CANCHIS', '', '', 8, 'A'),
                (74, '07', 'CHUMBIVILCAS', '', '', 8, 'A'),
                (75, '08', 'ESPINAR', '', '', 8, 'A'),
                (76, '09', 'LA CONVENCIÓN', '', '', 8, 'A'),
                (77, '10', 'PARURO', '', '', 8, 'A'),
                (78, '11', 'PAUCARTAMBO', '', '', 8, 'A'),
                (79, '12', 'QUISPICANCHI', '', '', 8, 'A'),
                (80, '13', 'URUBAMBA', '', '', 8, 'A'),
                (81, '01', 'HUANCAVELICA', '', '', 9, 'A'),
                (82, '02', 'ACOBAMBA', '', '', 9, 'A'),
                (83, '03', 'ANGARAES', '', '', 9, 'A'),
                (84, '04', 'CASTROVIRREYNA', '', '', 9, 'A'),
                (85, '05', 'CHURCAMPA', '', '', 9, 'A'),
                (86, '06', 'HUAYTARÁ', '', '', 9, 'A'),
                (87, '07', 'TAYACAJA', '', '', 9, 'A'),
                (88, '01', 'HUÁNUCO', '', '', 10, 'A'),
                (89, '02', 'AMBO', '', '', 10, 'A'),
                (90, '03', 'DOS DE MAYO', '', '', 10, 'A'),
                (91, '04', 'HUACAYBAMBA', '', '', 10, 'A'),
                (92, '05', 'HUAMALÍES', '', '', 10, 'A'),
                (93, '06', 'LEONCIO PRADO', '', '', 10, 'A'),
                (94, '07', 'MARAÑÓN', '', '', 10, 'A'),
                (95, '08', 'PACHITEA', '', '', 10, 'A'),
                (96, '09', 'PUERTO INCA', '', '', 10, 'A'),
                (97, '10', 'LAURICOCHA', '', '', 10, 'A'),
                (98, '11', 'YAROWILCA', '', '', 10, 'A'),
                (99, '01', 'ICA', '', '', 11, 'A'),
                (100, '02', 'CHINCHA', '', '', 11, 'A'),
                (101, '03', 'NASCA', '', '', 11, 'A'),
                (102, '04', 'PALPA', '', '', 11, 'A'),
                (103, '05', 'PISCO', '', '', 11, 'A'),
                (104, '01', 'HUANCAYO', '', '', 12, 'A'),
                (105, '02', 'CONCEPCIÓN', '', '', 12, 'A'),
                (106, '03', 'CHANCHAMAYO', '', '', 12, 'A'),
                (107, '04', 'JAUJA', '', '', 12, 'A'),
                (108, '05', 'JUNÍN', '', '', 12, 'A'),
                (109, '06', 'SATIPO', '', '', 12, 'A'),
                (110, '07', 'TARMA', '', '', 12, 'A'),
                (111, '08', 'YAULI', '', '', 12, 'A'),
                (112, '09', 'CHUPACA', '', '', 12, 'A'),
                (113, '01', 'TRUJILLO', '', '', 13, 'A'),
                (114, '02', 'ASCOPE', '', '', 13, 'A'),
                (115, '03', 'BOLÍVAR', '', '', 13, 'A'),
                (116, '04', 'CHEPÉN', '', '', 13, 'A'),
                (117, '05', 'JULCÁN', '', '', 13, 'A'),
                (118, '06', 'OTUZCO', '', '', 13, 'A'),
                (119, '07', 'PACASMAYO', '', '', 13, 'A'),
                (120, '08', 'PATAZ', '', '', 13, 'A'),
                (121, '09', 'SÁNCHEZ CARRIÓN', '', '', 13, 'A'),
                (122, '10', 'SANTIAGO DE CHUCO', '', '', 13, 'A'),
                (123, '11', 'GRAN CHIMÚ', '', '', 13, 'A'),
                (124, '12', 'VIRÚ', '', '', 13, 'A'),
                (125, '01', 'CHICLAYO', '', '', 14, 'A'),
                (126, '02', 'FERREÑAFE', '', '', 14, 'A'),
                (127, '03', 'LAMBAYEQUE', '', '', 14, 'A'),
                (128, '01', 'LIMA METROPOLITANA', '', '', 15, 'A'),
                (129, '02', 'BARRANCA', '', '', 15, 'A'),
                (130, '03', 'CAJATAMBO', '', '', 15, 'A'),
                (131, '04', 'CANTA', '', '', 15, 'A'),
                (132, '05', 'CAÑETE', '', '', 15, 'A'),
                (133, '06', 'HUARAL', '', '', 15, 'A'),
                (134, '07', 'HUAROCHIRÍ', '', '', 15, 'A'),
                (135, '08', 'HUAURA', '', '', 15, 'A'),
                (136, '09', 'OYÓN', '', '', 15, 'A'),
                (137, '10', 'YAUYOS', '', '', 15, 'A'),
                (138, '01', 'MAYNAS', '', '', 16, 'A'),
                (139, '02', 'ALTO AMAZONAS', '', '', 16, 'A'),
                (140, '03', 'LORETO', '', '', 16, 'A'),
                (141, '04', 'MARISCAL RAMÓN CASTILLA', '', '', 16, 'A'),
                (142, '05', 'REQUENA', '', '', 16, 'A'),
                (143, '06', 'UCAYALI', '', '', 16, 'A'),
                (144, '07', 'DATEM DEL MARAÑÓN', '', '', 16, 'A'),
                (145, '08', 'PUTUMAYO', '', '', 16, 'A'),
                (146, '01', 'TAMBOPATA', '', '', 17, 'A'),
                (147, '02', 'MANU', '', '', 17, 'A'),
                (148, '03', 'TAHUAMANU', '', '', 17, 'A'),
                (149, '01', 'MARISCAL NIETO', '', '', 18, 'A'),
                (150, '02', 'GENERAL SÁNCHEZ CERRO', '', '', 18, 'A'),
                (151, '03', 'ILO', '', '', 18, 'A'),
                (152, '01', 'PASCO', '', '', 19, 'A'),
                (153, '02', 'DANIEL ALCIDES CARRIÓN', '', '', 19, 'A'),
                (154, '03', 'OXAPAMPA', '', '', 19, 'A'),
                (155, '01', 'PIURA', '', '', 20, 'A'),
                (156, '02', 'AYABACA', '', '', 20, 'A'),
                (157, '03', 'HUANCABAMBA', '', '', 20, 'A'),
                (158, '04', 'MORROPÓN', '', '', 20, 'A'),
                (159, '05', 'PAITA', '', '', 20, 'A'),
                (160, '06', 'SULLANA', '', '', 20, 'A'),
                (161, '07', 'TALARA', '', '', 20, 'A'),
                (162, '08', 'SECHURA', '', '', 20, 'A'),
                (163, '01', 'PUNO', '', '', 21, 'A'),
                (164, '02', 'AZÁNGARO', '', '', 21, 'A'),
                (165, '03', 'CARABAYA', '', '', 21, 'A'),
                (166, '04', 'CHUCUITO', '', '', 21, 'A'),
                (167, '05', 'EL COLLAO', '', '', 21, 'A'),
                (168, '06', 'HUANCANÉ', '', '', 21, 'A'),
                (169, '07', 'LAMPA', '', '', 21, 'A'),
                (170, '08', 'MELGAR', '', '', 21, 'A'),
                (171, '09', 'MOHO', '', '', 21, 'A'),
                (172, '10', 'SAN ANTONIO DE PUTINA', '', '', 21, 'A'),
                (173, '11', 'SAN ROMÁN', '', '', 21, 'A'),
                (174, '12', 'SANDIA', '', '', 21, 'A'),
                (175, '13', 'YUNGUYO', '', '', 21, 'A'),
                (176, '01', 'MOYOBAMBA', '', '', 22, 'A'),
                (177, '02', 'BELLAVISTA', '', '', 22, 'A'),
                (178, '03', 'EL DORADO', '', '', 22, 'A'),
                (179, '04', 'HUALLAGA', '', '', 22, 'A'),
                (180, '05', 'LAMAS', '', '', 22, 'A'),
                (181, '06', 'MARISCAL CÁCERES', '', '', 22, 'A'),
                (182, '07', 'PICOTA', '', '', 22, 'A'),
                (183, '08', 'RIOJA', '', '', 22, 'A'),
                (184, '09', 'SAN MARTÍN', '', '', 22, 'A'),
                (185, '10', 'TOCACHE', '', '', 22, 'A'),
                (186, '01', 'TACNA', '', '', 23, 'A'),
                (187, '02', 'CANDARAVE', '', '', 23, 'A'),
                (188, '03', 'JORGE BASADRE', '', '', 23, 'A'),
                (189, '04', 'TARATA', '', '', 23, 'A'),
                (190, '01', 'TUMBES', '', '', 24, 'A'),
                (191, '02', 'CONTRALMIRANTE VILLAR', '', '', 24, 'A'),
                (192, '03', 'ZARUMILLA', '', '', 24, 'A'),
                (193, '01', 'CORONEL PORTILLO', '', '', 25, 'A'),
                (194, '02', 'ATALAYA', '', '', 25, 'A'),
                (195, '03', 'PADRE ABAD', '', '', 25, 'A'),
                (196, '04', 'PURÚS', '', '', 25, 'A');
    INSERT INTO public.saeciud (ciud_cod_ciud, ciud_cod_pais, ciud_nom_ciud, ciud_cod_prov, ciud_tip_ciud, ciud_cod_sri, ciud_cod_urbano, ciud_zip_code) 
                        VALUES  
                                (1, 28, 'CHACHAPOYAS', 1, 0, '0', 0, '0'),
                                (2, 28, 'BAGUA', 1, 0, '0', 0, '0'),
                                (3, 28, 'BONGARÁ', 1, 0, '0', 0, '0'),
                                (4, 28, 'CONDORCANQUI', 1, 0, '0', 0, '0'),
                                (5, 28, 'LUYA', 1, 0, '0', 0, '0'),
                                (6, 28, 'RODRÍGUEZ DE MENDOZA', 1, 0, '0', 0, '0'),
                                (7, 28, 'UTCUBAMBA', 1, 0, '0', 0, '0'),
                                (8, 28, 'HUARAZ', 2, 0, '0', 0, '0'),
                                (9, 28, 'AIJA', 2, 0, '0', 0, '0'),
                                (10, 28, 'ANTONIO RAYMONDI', 2, 0, '0', 0, '0'),
                                (11, 28, 'ASUNCIÓN', 2, 0, '0', 0, '0'),
                                (12, 28, 'BOLOGNESI', 2, 0, '0', 0, '0'),
                                (13, 28, 'CARHUAZ', 2, 0, '0', 0, '0'),
                                (14, 28, 'CARLOS F. FITZCARRALD', 2, 0, '0', 0, '0'),
                                (15, 28, 'CASMA', 2, 0, '0', 0, '0'),
                                (16, 28, 'CORONGO', 2, 0, '0', 0, '0'),
                                (17, 28, 'HUARI', 2, 0, '0', 0, '0'),
                                (18, 28, 'HUARMEY', 2, 0, '0', 0, '0'),
                                (19, 28, 'HUAYLAS', 2, 0, '0', 0, '0'),
                                (20, 28, 'MARISCAL LUZURIAGA', 2, 0, '0', 0, '0'),
                                (21, 28, 'OCROS', 2, 0, '0', 0, '0'),
                                (22, 28, 'PALLASCA', 2, 0, '0', 0, '0'),
                                (23, 28, 'POMABAMBA', 2, 0, '0', 0, '0'),
                                (24, 28, 'RECUAY', 2, 0, '0', 0, '0'),
                                (25, 28, 'SANTA', 2, 0, '0', 0, '0'),
                                (26, 28, 'SIHUAS', 2, 0, '0', 0, '0'),
                                (27, 28, 'YUNGAY', 2, 0, '0', 0, '0'),
                                (28, 28, 'ABANCAY', 3, 0, '0', 0, '0'),
                                (29, 28, 'ANDAHUAYLAS', 3, 0, '0', 0, '0'),
                                (30, 28, 'ANTABAMBA', 3, 0, '0', 0, '0'),
                                (31, 28, 'AYMARAES', 3, 0, '0', 0, '0'),
                                (32, 28, 'COTABAMBAS', 3, 0, '0', 0, '0'),
                                (33, 28, 'CHINCHEROS', 3, 0, '0', 0, '0'),
                                (34, 28, 'GRAU', 3, 0, '0', 0, '0'),
                                (35, 28, 'AREQUIPA', 4, 0, '0', 0, '0'),
                                (36, 28, 'CAMANÁ', 4, 0, '0', 0, '0'),
                                (37, 28, 'CARAVELÍ', 4, 0, '0', 0, '0'),
                                (38, 28, 'CASTILLA', 4, 0, '0', 0, '0'),
                                (39, 28, 'CAYLLOMA', 4, 0, '0', 0, '0'),
                                (40, 28, 'CONDESUYOS', 4, 0, '0', 0, '0'),
                                (41, 28, 'ISLAY', 4, 0, '0', 0, '0'),
                                (42, 28, 'LA UNIÓN', 4, 0, '0', 0, '0'),
                                (43, 28, 'HUAMANGA', 5, 0, '0', 0, '0'),
                                (44, 28, 'CANGALLO', 5, 0, '0', 0, '0'),
                                (45, 28, 'HUANCA SANCOS', 5, 0, '0', 0, '0'),
                                (46, 28, 'HUANTA', 5, 0, '0', 0, '0'),
                                (47, 28, 'LA MAR', 5, 0, '0', 0, '0'),
                                (48, 28, 'LUCANAS', 5, 0, '0', 0, '0'),
                                (49, 28, 'PARINACOCHAS', 5, 0, '0', 0, '0'),
                                (50, 28, 'PÁUCAR DEL SARA SARA', 5, 0, '0', 0, '0'),
                                (51, 28, 'SUCRE', 5, 0, '0', 0, '0'),
                                (52, 28, 'VÍCTOR FAJARDO', 5, 0, '0', 0, '0'),
                                (53, 28, 'VILCAS HUAMÁN', 5, 0, '0', 0, '0'),
                                (54, 28, 'CAJAMARCA', 6, 0, '0', 0, '0'),
                                (55, 28, 'CAJABAMBA', 6, 0, '0', 0, '0'),
                                (56, 28, 'CELENDÍN', 6, 0, '0', 0, '0'),
                                (57, 28, 'CHOTA', 6, 0, '0', 0, '0'),
                                (58, 28, 'CONTUMAZÁ', 6, 0, '0', 0, '0'),
                                (59, 28, 'CUTERVO', 6, 0, '0', 0, '0'),
                                (60, 28, 'HUALGAYOC', 6, 0, '0', 0, '0'),
                                (61, 28, 'JAÉN', 6, 0, '0', 0, '0'),
                                (62, 28, 'SAN IGNACIO', 6, 0, '0', 0, '0'),
                                (63, 28, 'SAN MARCOS', 6, 0, '0', 0, '0'),
                                (64, 28, 'SAN MIGUEL', 6, 0, '0', 0, '0'),
                                (65, 28, 'SAN PABLO', 6, 0, '0', 0, '0'),
                                (66, 28, 'SANTA CRUZ', 6, 0, '0', 0, '0'),
                                (67, 28, 'CALLAO', 7, 0, '0', 0, '0'),
                                (68, 28, 'CUSCO', 8, 0, '0', 0, '0'),
                                (69, 28, 'ACOMAYO', 8, 0, '0', 0, '0'),
                                (70, 28, 'ANTA', 8, 0, '0', 0, '0'),
                                (71, 28, 'CALCA', 8, 0, '0', 0, '0'),
                                (72, 28, 'CANAS', 8, 0, '0', 0, '0'),
                                (73, 28, 'CANCHIS', 8, 0, '0', 0, '0'),
                                (74, 28, 'CHUMBIVILCAS', 8, 0, '0', 0, '0'),
                                (75, 28, 'ESPINAR', 8, 0, '0', 0, '0'),
                                (76, 28, 'LA CONVENCIÓN', 8, 0, '0', 0, '0'),
                                (77, 28, 'PARURO', 8, 0, '0', 0, '0'),
                                (78, 28, 'PAUCARTAMBO', 8, 0, '0', 0, '0'),
                                (79, 28, 'QUISPICANCHI', 8, 0, '0', 0, '0'),
                                (80, 28, 'URUBAMBA', 8, 0, '0', 0, '0'),
                                (81, 28, 'HUANCAVELICA', 9, 0, '0', 0, '0'),
                                (82, 28, 'ACOBAMBA', 9, 0, '0', 0, '0'),
                                (83, 28, 'ANGARAES', 9, 0, '0', 0, '0'),
                                (84, 28, 'CASTROVIRREYNA', 9, 0, '0', 0, '0'),
                                (85, 28, 'CHURCAMPA', 9, 0, '0', 0, '0'),
                                (86, 28, 'HUAYTARÁ', 9, 0, '0', 0, '0'),
                                (87, 28, 'TAYACAJA', 9, 0, '0', 0, '0'),
                                (88, 28, 'HUÁNUCO', 10, 0, '0', 0, '0'),
                                (89, 28, 'AMBO', 10, 0, '0', 0, '0'),
                                (90, 28, 'DOS DE MAYO', 10, 0, '0', 0, '0'),
                                (91, 28, 'HUACAYBAMBA', 10, 0, '0', 0, '0'),
                                (92, 28, 'HUAMALÍES', 10, 0, '0', 0, '0'),
                                (93, 28, 'LEONCIO PRADO', 10, 0, '0', 0, '0'),
                                (94, 28, 'MARAÑÓN', 10, 0, '0', 0, '0'),
                                (95, 28, 'PACHITEA', 10, 0, '0', 0, '0'),
                                (96, 28, 'PUERTO INCA', 10, 0, '0', 0, '0'),
                                (97, 28, 'LAURICOCHA', 10, 0, '0', 0, '0'),
                                (98, 28, 'YAROWILCA', 10, 0, '0', 0, '0'),
                                (99, 28, 'ICA', 11, 0, '0', 0, '0'),
                                (100, 28, 'CHINCHA', 11, 0, '0', 0, '0'),
                                (101, 28, 'NASCA', 11, 0, '0', 0, '0'),
                                (102, 28, 'PALPA', 11, 0, '0', 0, '0'),
                                (103, 28, 'PISCO', 11, 0, '0', 0, '0'),
                                (104, 28, 'HUANCAYO', 12, 0, '0', 0, '0'),
                                (105, 28, 'CONCEPCIÓN', 12, 0, '0', 0, '0'),
                                (106, 28, 'CHANCHAMAYO', 12, 0, '0', 0, '0'),
                                (107, 28, 'JAUJA', 12, 0, '0', 0, '0'),
                                (108, 28, 'JUNÍN', 12, 0, '0', 0, '0'),
                                (109, 28, 'SATIPO', 12, 0, '0', 0, '0'),
                                (110, 28, 'TARMA', 12, 0, '0', 0, '0'),
                                (111, 28, 'YAULI', 12, 0, '0', 0, '0'),
                                (112, 28, 'CHUPACA', 12, 0, '0', 0, '0'),
                                (113, 28, 'TRUJILLO', 13, 0, '0', 0, '0'),
                                (114, 28, 'ASCOPE', 13, 0, '0', 0, '0'),
                                (115, 28, 'BOLÍVAR', 13, 0, '0', 0, '0'),
                                (116, 28, 'CHEPÉN', 13, 0, '0', 0, '0'),
                                (117, 28, 'JULCÁN', 13, 0, '0', 0, '0'),
                                (118, 28, 'OTUZCO', 13, 0, '0', 0, '0'),
                                (119, 28, 'PACASMAYO', 13, 0, '0', 0, '0'),
                                (120, 28, 'PATAZ', 13, 0, '0', 0, '0'),
                                (121, 28, 'SÁNCHEZ CARRIÓN', 13, 0, '0', 0, '0'),
                                (122, 28, 'SANTIAGO DE CHUCO', 13, 0, '0', 0, '0'),
                                (123, 28, 'GRAN CHIMÚ', 13, 0, '0', 0, '0'),
                                (124, 28, 'VIRÚ', 13, 0, '0', 0, '0'),
                                (125, 28, 'CHICLAYO', 14, 0, '0', 0, '0'),
                                (126, 28, 'FERREÑAFE', 14, 0, '0', 0, '0'),
                                (127, 28, 'LAMBAYEQUE', 14, 0, '0', 0, '0'),
                                (128, 28, 'LIMA METROPOLITANA', 15, 0, '0', 0, '0'),
                                (129, 28, 'BARRANCA', 15, 0, '0', 0, '0'),
                                (130, 28, 'CAJATAMBO', 15, 0, '0', 0, '0'),
                                (131, 28, 'CANTA', 15, 0, '0', 0, '0'),
                                (132, 28, 'CAÑETE', 15, 0, '0', 0, '0'),
                                (133, 28, 'HUARAL', 15, 0, '0', 0, '0'),
                                (134, 28, 'HUAROCHIRÍ', 15, 0, '0', 0, '0'),
                                (135, 28, 'HUAURA', 15, 0, '0', 0, '0'),
                                (136, 28, 'OYÓN', 15, 0, '0', 0, '0'),
                                (137, 28, 'YAUYOS', 15, 0, '0', 0, '0'),
                                (138, 28, 'MAYNAS', 16, 0, '0', 0, '0'),
                                (139, 28, 'ALTO AMAZONAS', 16, 0, '0', 0, '0'),
                                (140, 28, 'LORETO', 16, 0, '0', 0, '0'),
                                (141, 28, 'MARISCAL RAMÓN CASTILLA', 16, 0, '0', 0, '0'),
                                (142, 28, 'REQUENA', 16, 0, '0', 0, '0'),
                                (143, 28, 'UCAYALI', 16, 0, '0', 0, '0'),
                                (144, 28, 'DATEM DEL MARAÑÓN', 16, 0, '0', 0, '0'),
                                (145, 28, 'PUTUMAYO', 16, 0, '0', 0, '0'),
                                (146, 28, 'TAMBOPATA', 17, 0, '0', 0, '0'),
                                (147, 28, 'MANU', 17, 0, '0', 0, '0'),
                                (148, 28, 'TAHUAMANU', 17, 0, '0', 0, '0'),
                                (149, 28, 'MARISCAL NIETO', 18, 0, '0', 0, '0'),
                                (150, 28, 'GENERAL SÁNCHEZ CERRO', 18, 0, '0', 0, '0'),
                                (151, 28, 'ILO', 18, 0, '0', 0, '0'),
                                (152, 28, 'PASCO', 19, 0, '0', 0, '0'),
                                (153, 28, 'DANIEL ALCIDES CARRIÓN', 19, 0, '0', 0, '0'),
                                (154, 28, 'OXAPAMPA', 19, 0, '0', 0, '0'),
                                (155, 28, 'PIURA', 20, 0, '0', 0, '0'),
                                (156, 28, 'AYABACA', 20, 0, '0', 0, '0'),
                                (157, 28, 'HUANCABAMBA', 20, 0, '0', 0, '0'),
                                (158, 28, 'MORROPÓN', 20, 0, '0', 0, '0'),
                                (159, 28, 'PAITA', 20, 0, '0', 0, '0'),
                                (160, 28, 'SULLANA', 20, 0, '0', 0, '0'),
                                (161, 28, 'TALARA', 20, 0, '0', 0, '0'),
                                (162, 28, 'SECHURA', 20, 0, '0', 0, '0'),
                                (163, 28, 'PUNO', 21, 0, '0', 0, '0'),
                                (164, 28, 'AZÁNGARO', 21, 0, '0', 0, '0'),
                                (165, 28, 'CARABAYA', 21, 0, '0', 0, '0'),
                                (166, 28, 'CHUCUITO', 21, 0, '0', 0, '0'),
                                (167, 28, 'EL COLLAO', 21, 0, '0', 0, '0'),
                                (168, 28, 'HUANCANÉ', 21, 0, '0', 0, '0'),
                                (169, 28, 'LAMPA', 21, 0, '0', 0, '0'),
                                (170, 28, 'MELGAR', 21, 0, '0', 0, '0'),
                                (171, 28, 'MOHO', 21, 0, '0', 0, '0'),
                                (172, 28, 'SAN ANTONIO DE PUTINA', 21, 0, '0', 0, '0'),
                                (173, 28, 'SAN ROMÁN', 21, 0, '0', 0, '0'),
                                (174, 28, 'SANDIA', 21, 0, '0', 0, '0'),
                                (175, 28, 'YUNGUYO', 21, 0, '0', 0, '0'),
                                (176, 28, 'MOYOBAMBA', 22, 0, '0', 0, '0'),
                                (177, 28, 'BELLAVISTA', 22, 0, '0', 0, '0'),
                                (178, 28, 'EL DORADO', 22, 0, '0', 0, '0'),
                                (179, 28, 'HUALLAGA', 22, 0, '0', 0, '0'),
                                (180, 28, 'LAMAS', 22, 0, '0', 0, '0'),
                                (181, 28, 'MARISCAL CÁCERES', 22, 0, '0', 0, '0'),
                                (182, 28, 'PICOTA', 22, 0, '0', 0, '0'),
                                (183, 28, 'RIOJA', 22, 0, '0', 0, '0'),
                                (184, 28, 'SAN MARTÍN', 22, 0, '0', 0, '0'),
                                (185, 28, 'TOCACHE', 22, 0, '0', 0, '0'),
                                (186, 28, 'TACNA', 23, 0, '0', 0, '0'),
                                (187, 28, 'CANDARAVE', 23, 0, '0', 0, '0'),
                                (188, 28, 'JORGE BASADRE', 23, 0, '0', 0, '0'),
                                (189, 28, 'TARATA', 23, 0, '0', 0, '0'),
                                (190, 28, 'TUMBES', 24, 0, '0', 0, '0'),
                                (191, 28, 'CONTRALMIRANTE VILLAR', 24, 0, '0', 0, '0'),
                                (192, 28, 'ZARUMILLA', 24, 0, '0', 0, '0'),
                                (193, 28, 'CORONEL PORTILLO', 25, 0, '0', 0, '0'),
                                (194, 28, 'ATALAYA', 25, 0, '0', 0, '0'),
                                (195, 28, 'PADRE ABAD', 25, 0, '0', 0, '0'),
                                (196, 28, 'PURÚS', 25, 0, '0', 0, '0');
    INSERT INTO public.saeparr (parr_cod_parr, parr_cod_char, parr_cod_cant, parr_des_parr, parr_zip_code, parr_cod_ciud) 
                        VALUES (1, '1', 1, 'CHACHAPOYAS', '', '1');
COMMIT;